env:
  browser: true
  es2021: true
extends:
  - airbnb
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - "@typescript-eslint"
ignorePatterns: ["lib"]
rules: { "prettier/prettier": "error" }
